Failed to create secure directory (/run/user/196973/pulse): No such file or directory
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
Blender 2.90.1 (hash 3e85bb34d0d7 built 2020-09-23 08:34:47)
/run/user/196973/gvfs/ non-existent directory
found bundled python: /home/yyf/CommonFate/Blender/2.90/python
Info: Deleted 1 object(s)
Info: Deleted 1 object(s)
Huffman table 0x00 was not defined
Traceback (most recent call last):
  File "/home/yyf/CommonFate/blender_qrotation.py", line 268, in <module>
    main()
  File "/home/yyf/CommonFate/blender_qrotation.py", line 240, in main
    texture.save(texture_file)
  File "/home/yyf/CommonFate/Blender/2.90/python/lib/python3.7/PIL/Image.py", line 2151, in save
    save_handler(self, fp, filename)
  File "/home/yyf/CommonFate/Blender/2.90/python/lib/python3.7/PIL/JpegImagePlugin.py", line 762, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "/home/yyf/CommonFate/Blender/2.90/python/lib/python3.7/PIL/ImageFile.py", line 544, in _save
    raise OSError(f"encoder error {s} when writing image file")
OSError: encoder error -2 when writing image file
Info: Deleted 1 object(s)
Info: Deleted 1 object(s)
PROCESSING  OBJECTS/SCENE_064

Blender quit
